name: Environment Secret Demo

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production   # <- links this job to the environment
    steps:
      - name: Use environment secret
        run: |
          echo "Deploying with production DB password"
          echo "Masked value: $PROD_DB_PASSWORD"
        env:
          PROD_DB_PASSWORD: ${{ secrets.PROD_DB_PASSWORD }}