name: Org Secret Demo

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Use organization secret
        run: |
          echo "Organization secret works!"
          echo "Masked value: $ORG_API_KEY"
        env:
          ORG_API_KEY: ${{ secrets.ORG_API_KEY }}